name: Deploy

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hynek/build-and-inspect-python-package@v1

  release-pypi:
    name: Publish released package to pypi.org
    if: |
      github.repository_owner == 'niranjanneeru'
      && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs: build-package

    permissions:
      id-token: write

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
